apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: {{ .Values.myservice.type }}
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: {{ .Values.myservice.nodeport }}
  selector:
    app: jenkins
